In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread("modi.jpg")

## Images as a numpy array

In [3]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


 This is stored as a 3D numpy array because we stored a color image inside the img variable

### Display the image

In [4]:
cv2.imshow("PM",img)
cv2.waitKey()
cv2.destroyAllWindows()

This will display the image 

#### Save the image

In [5]:
cv2.imwrite("namo.png",img)

True

### Resize the image

In [6]:
img = cv2.imread("modi.jpg")
resize_img = cv2.resize(img,(500,500))

cv2.imshow("PM",resize_img)
cv2.waitKey()
cv2.destroyAllWindows()

### Face Detection using HAAR Cascade Classifier

In [20]:
face_classifier = cv2.CascadeClassifier("Haarcascades/haarcascade_frontalface_default.xml")

image = cv2.imread("Modi.jpg")

resize_img = cv2.resize(image,(500,500))

gray = cv2.cvtColor(resize_img,cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray,1.05,5)

In [21]:
print(faces)

[[205  79 217 217]]


In [25]:
if faces is ():
    print("No faces found")
    
for (x,y,w,h) in faces:
    cv2.rectangle(resize_img,(x,y),(x+w,y+h),(0,0,255),3)
    
    
cv2.imshow("PM",resize_img)    
cv2.waitKey()
cv2.destroyAllWindows()

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Deepak Mehta\AppData\Local\Temp\ipykernel_14988\4049081728.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


### Face and eye HAAR cascade classifier

In [42]:
face_classifier = cv2.CascadeClassifier("Haarcascades/haarcascade_frontalface_default.xml")
# eye_classifier  = cv2.CascadeClassifier("Haarcascade/haarcascade_eye.xml")
eye_classifier  = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_eye.xml")



In [43]:
image = cv2.imread("Modi.jpg")
resize_img = cv2.resize(image,(500,500))
gray = cv2.cvtColor(resize_img,cv2.COLOR_BGR2GRAY)

In [44]:
faces = face_classifier.detectMultiScale(gray,1.3,5)


In [45]:
print(faces)

[[205  80 216 216]]


In [48]:

if faces is ():
    print("No faces found")
    
for (x,y,w,h) in faces:
    cv2.rectangle(resize_img,(x,y),(x+w,y+h),(0,0,255),3)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = resize_img[y:y+h,x:x+w]
    
    eyes = eye_classifier.detectMultiScale(roi_gray)
    
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,25,0),2)
    
    
cv2.imshow("PM",resize_img)    
cv2.waitKey()
cv2.destroyAllWindows()


<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Deepak Mehta\AppData\Local\Temp\ipykernel_14988\3280599139.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [39]:
cv2.imshow("PM",roi_color)
cv2.waitKey()
cv2.destroyAllWindows()

In [59]:
face_classifier = cv2.CascadeClassifier("Haarcascades/haarcascade_frontalface_default.xml")
# eye_classifier  = cv2.CascadeClassifier("Haarcascade/haarcascade_eye.xml")
eye_classifier  = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_eye.xml")

image = cv2.imread("modi.jpg")
resize_img = cv2.resize(image,(500,500))
gray = cv2.cvtColor(resize_img,cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray,1.3,5)


if faces is ():
    print("No faces found")
    
for (x,y,w,h) in faces:
    cv2.rectangle(resize_img,(x,y),(x+w,y+h),(0,0,255),3)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = resize_img[y:y+h,x:x+w]
    
    eyes = eye_classifier.detectMultiScale(roi_gray)
    
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,255),2)
    
    
cv2.imshow("PM",resize_img)    
cv2.waitKey()
cv2.destroyAllWindows()



<>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Deepak Mehta\AppData\Local\Temp\ipykernel_14988\1150531875.py:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():
